language: python
python: 2.7
env:
  global:
    - COVERAGE_CMD="coverage run --append --source vcr_facebook,tests -m"
    - COVERAGE_DEP=coverage
install:
  - pip install tox coveralls
script:
  - tox
after_script:
  - coveralls